import { useQuery } from '@apollo/client'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { UserGetAllDocument, UserGetAllQuery, UserGetAllQueryVariables, useUserGetAllQuery, useUserGetByidQuery } from '../generated'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {

  // const { data, error, loading } = useQuery<UserGetAllQuery, UserGetAllQueryVariables>(UserGetAllDocument); 
  // const { data, error, loading } = useUserGetAllQuery();
  const { data, loading, error } = useUserGetAllQuery({
       variables: {
       },
     });
  
  if (loading)
  return (
    <main className={styles.main}>
        Loading...
    </main>
    );

    if (error)
    return (
      <main className={styles.main}>
          {error.message}
      </main>
      );

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {/* <p>Number of users: {data?.userGetAll.length}</p>
        <p>avatar: {data?.userGetAll[1].avatar}</p>
        <p>id: {data?.userGetAll[1].id}</p>
        <p>Name: {data?.userGetAll[1].name}</p>
        <p>createdAt: {data?.userGetAll[1].createdAt}</p>
        <p>updatedAt: {data?.userGetAll[1].updatedAt}</p>
        <p>email: {data?.userGetAll[1].email}</p>
        <p>Lastscore: {data?.userGetAll[1].lastScore}</p>
        <p>Bestscore: {data?.userGetAll[1].bestScore}</p>
        */}
        
      {!data
        ? null
        : data.userGetAll.map((e) => {
            return <p key={e.id}>{e.id} ** {e.name} ** {e.createdAt} ** {e.updatedAt} ** {e.email} ** {e.lastScore} ** {e.bestScore}</p>;
          })
      }

     
      
  
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
